CONCURRENT_REQUESTS=$2
TOTAL_REQUESTS=$1

./test-raw.sh $TOTAL_REQUESTS $CONCURRENT_REQUESTS
./test-pm-raw.sh $TOTAL_REQUESTS $CONCURRENT_REQUESTS
./test-pm.sh $TOTAL_REQUESTS $CONCURRENT_REQUESTS
./test-sf.sh $TOTAL_REQUESTS $CONCURRENT_REQUESTS
